<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>21a3eefb-8ba3-4206-be9b-8e133a49d982</elementGuidId>
    <imagePath></imagePath>
    <name>button_back_to_products</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'back-to-products')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>back-to-products</value>
        <webElementGuid>f8827485-5170-40e0-ad2d-73d7c3c4e724</webElementGuid>
    </webElementProperties>
</WebElementEntity>