<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f7fe9ea4-febf-4b3a-b5bd-d5331263bb35</elementGuidId>
    <imagePath></imagePath>
    <name>button_add_to_cart_sauce_labs_onesie</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'add-to-cart-sauce-labs-onesie')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>add-to-cart-sauce-labs-onesie</value>
        <webElementGuid>6c829905-a9f9-496c-a887-6df9db97592e</webElementGuid>
    </webElementProperties>
</WebElementEntity>