<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0167574e-2259-4a57-8b65-12f8dfb92557</elementGuidId>
    <imagePath></imagePath>
    <name>input_user_name</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#user-name</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'user-name') and equals(@name,'user-name') and equals(@class,'input_error form_input')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>input_error form_input</value>
        <webElementGuid>c9dfffad-e067-4450-8e04-b0ae47cc76cd</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>user-name</value>
        <webElementGuid>b6b23040-d9cd-4ce8-83d9-e458fa611aab</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>user-name</value>
        <webElementGuid>61fe282b-c9c7-4fa4-b3d5-5139ce6f498a</webElementGuid>
    </webElementProperties>
</WebElementEntity>