<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9440de95-c259-4284-8a55-4a9cc4539999</elementGuidId>
    <imagePath></imagePath>
    <name>input_user_name</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#user-name</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'user-name') and equals(@name,'user-name') and equals(@class,'input_error form_input')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>input_error form_input</value>
        <webElementGuid>dc50e0f9-39c8-42a1-bb9e-2682195b7ebf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>user-name</value>
        <webElementGuid>4f557efb-23cf-4624-a9c9-c59b912ff2f2</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>user-name</value>
        <webElementGuid>5c06a724-6b9f-4595-949e-a9e93aa8253e</webElementGuid>
    </webElementProperties>
</WebElementEntity>