<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>97d131f4-1de0-4039-9f37-f23bc394c394</elementGuidId>
    <imagePath></imagePath>
    <name>input_user_name</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#user-name</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'user-name') and equals(@name,'user-name') and equals(@class,'input_error form_input')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>input_error form_input</value>
        <webElementGuid>31378ac3-4d7b-480c-b723-d059b39cd05c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>user-name</value>
        <webElementGuid>c874cadd-9a04-4901-9401-e5307810e5b0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>user-name</value>
        <webElementGuid>11490ee5-2223-461e-a04f-ba229684e785</webElementGuid>
    </webElementProperties>
</WebElementEntity>