<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7d41e758-0cb0-4f30-9af3-3db1176d16f5</elementGuidId>
    <imagePath></imagePath>
    <name>input_login_button</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#login-button</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'login-button') and equals(@name,'login-button') and equals(@class,'submit-button btn_action')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>submit-button btn_action</value>
        <webElementGuid>af0e0f97-0111-48af-ad12-cad269959026</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>login-button</value>
        <webElementGuid>3f92751f-e35a-43cf-ac87-beaaabe36f71</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>login-button</value>
        <webElementGuid>aba75d89-29c2-481d-aef4-80cf93f1f4cb</webElementGuid>
    </webElementProperties>
</WebElementEntity>