<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8c0e07ac-4847-46b6-930b-88c2889651a9</elementGuidId>
    <imagePath></imagePath>
    <name>input_login_button</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#login-button</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'login-button') and equals(@name,'login-button') and equals(@class,'submit-button btn_action')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>submit-button btn_action</value>
        <webElementGuid>5675900d-52d2-4a89-a0b2-0e6c17972249</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>login-button</value>
        <webElementGuid>a0faaa8b-1b9a-4813-a7b3-60a0ae7dd167</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>login-button</value>
        <webElementGuid>3e0cecaa-2beb-48e7-a11a-48b70f21d90e</webElementGuid>
    </webElementProperties>
</WebElementEntity>