<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>404e257e-c9e9-4da4-b610-80a4ba539fe8</elementGuidId>
    <imagePath></imagePath>
    <name>input_login_button</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#login-button</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'login-button') and equals(@name,'login-button') and equals(@class,'submit-button btn_action')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>submit-button btn_action</value>
        <webElementGuid>a9e8beb1-8ee5-4f77-86c6-cd55ed40cffe</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>login-button</value>
        <webElementGuid>4e5ccac9-6aec-4877-8be7-474860b43121</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>login-button</value>
        <webElementGuid>21b81be8-1e66-4a2c-b6bc-2280f45116ad</webElementGuid>
    </webElementProperties>
</WebElementEntity>