<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>871beb29-ee24-4eef-9751-e5b0968ad9d0</elementGuidId>
    <imagePath></imagePath>
    <name>button_add_to_cart_sauce_labs_fleece_jacket</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[4]/div[2]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'add-to-cart-sauce-labs-fleece-jacket')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>add-to-cart-sauce-labs-fleece-jacket</value>
        <webElementGuid>740b5a84-df16-47dc-9bfd-7c4dc582d7a9</webElementGuid>
    </webElementProperties>
</WebElementEntity>