<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>008c5647-2b3b-4140-a3bc-1dc68035794e</elementGuidId>
    <imagePath></imagePath>
    <name>button_add_to_cart_test_allthethings_t_shirt_re</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[6]/div[2]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'add-to-cart-test.allthethings()-t-shirt-(red)')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>add-to-cart-test.allthethings()-t-shirt-(red)</value>
        <webElementGuid>a86b084e-6ba7-4286-a139-f4f07e1ce2bf</webElementGuid>
    </webElementProperties>
</WebElementEntity>