<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>89752a5c-64c8-446e-ac3f-4d11569b9507</elementGuidId>
    <imagePath></imagePath>
    <name>button_add_to_cart_sauce_labs_bolt_t_shirt</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'add-to-cart-sauce-labs-bolt-t-shirt')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>add-to-cart-sauce-labs-bolt-t-shirt</value>
        <webElementGuid>db5e5d85-f06b-482d-9605-e2deeb4f18d9</webElementGuid>
    </webElementProperties>
</WebElementEntity>