<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6f615c81-7ffb-4dca-84ef-d4cb7fd9c016</elementGuidId>
    <imagePath></imagePath>
    <name>button_remove_sauce_labs_bolt_t_shirt_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[4]/div[2]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'remove-sauce-labs-bolt-t-shirt')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>remove-sauce-labs-bolt-t-shirt</value>
        <webElementGuid>d386f2c2-430b-46d5-b4ae-a13b35c866d3</webElementGuid>
    </webElementProperties>
</WebElementEntity>