<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>11396171-2df6-4a88-a811-7c3906ea5eda</elementGuidId>
    <imagePath></imagePath>
    <name>button_remove_sauce_labs_bolt_t_shirt</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[3]/div[2]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'remove-sauce-labs-bolt-t-shirt')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>remove-sauce-labs-bolt-t-shirt</value>
        <webElementGuid>84065ffa-2342-4af7-a286-688f8e64f81d</webElementGuid>
    </webElementProperties>
</WebElementEntity>